name: Dclock
version: 1.0.0+1
publish_to: none
description: digital clock apps with alarm notifications
environment: 
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_local_notifications: ^12.0.3
  google_fonts: ^3.0.1
  flutter_secure_storage: ^6.0.0
  hive: ^2.2.3

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/background/
    - assets/background/illustration/
    - assets/avatar/

